services:
  # ML MODEL TRAINING SERVICE
  ml-train:
    build: .
    command: [ "python", "entrypoints/training.py" ]
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf

  # ML INFERENCE SERVICE
  ml-inference:
    build: .
    command: [ "python", "entrypoints/inference.py" ]
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
    depends_on:
      ml-train:
        condition: service_completed_successfully

  # WEB USER INTERFACE SERVICE
  app-ui:
    build: .
    command: [ "python", "entrypoints/app_ui.py" ]
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
    depends_on:
      - ml-inference

  # MLFLOW TRACKING DASHBOARD
  mlflow-ui:
    build: .
    command: [ "mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "file:///app/data/09_tracking" ]
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
